version: "2.5"

services:
  mysql:
    image: mysql:8.0.33
    platform: linux/amd64
    container_name: ruty-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ruty_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: ruty
      MYSQL_PASSWORD: bunnies
#    volumes:
#      - db_data:/var/lib/mysql
#      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    networks:
      - app-network

  ruty-server:
    image: ghcr.io/central-makeus/ruty-server-deploy:latest
    platform: linux/amd64
    container_name: ruty-server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ruty-mysql:3306/ruty_db
      SPRING_DATASOURCE_USERNAME: ruty
      SPRING_DATASOURCE_PASSWORD: bunnies
    ports:
      - "80:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

