server:
  port: 8080

spring:
  profiles:
    include: oauth, jwt, ai

  application:
    name: ruty-server

  datasource-data:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # localhost
    jdbc-url: jdbc:mysql://localhost:3306/ruty_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    # gcp vm mysql
#    url: jdbc:mysql://34.59.214.93:3306/ruty_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # docker mysql
#    url: jdbc:mysql://ruty-mysql:3306/ruty_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ruty
    password: bunnies

  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
      # localhost
    jdbc-url: jdbc:mysql://localhost:3306/ruty_db_meta?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      # gcp vm mysql
      #    url: jdbc:mysql://34.59.214.93:3306/ruty_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      # docker mysql
#      url: jdbc:mysql://ruty-mysql:3306/ruty_db_meta?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ruty
    password: bunnies

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: org/springframework/batch/core/schema-mysql.sql
