jwt:
  secretKey: songseonghuncandoanythingiwanttocompletethisprojectdonotlazyalldaysingsangssongbunniesfighting

  access:
    expiration: 1800000 # 30분
    header: Authorization

  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh
