jwt:
  secretKey: songseonghuncandoanythingiwanttocompletethisprojectdonotlazyalldaysingsangssongbunniesfighting

  access:
    expiration: 1800000000 # 30분
#    expiration: 18000000000 # 3시간
    header: Authorization

  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh
